_target_: src.models.bls_module.BLSLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00001
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.bls.GDBLS
  input_shape: [3, 32, 32]
  fb_depth: 1
  filters: [128, 160, 192]
  overall_dropout: 0.1

# compile model for faster training with pytorch 2.0
compile: true
