_target_: src.models.bls_module.BLSLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 5e-3
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.bls_v2.GDBLS
  num_classes: 10,
  input_shape: (3,32,32),
  filters: [128,160,192],
  num_heads: [1,2,4],
  block_drop: 0.1,
  overall_drop: 0.1

# compile model for faster training with pytorch 2.0
compile: true
