_target_: src.models.bls_module.BLSLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00001
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.bls_v1.GDBLS
  num_classes: 10
  input_channels: 3
  filters: [128, 160, 192]
  num_layers: 4
  dropout_rate: 0.5
  block_drop_rate: 0.1

# compile model for faster training with pytorch 2.0
compile: true
